### ISSUE TITLE
liquibase data installation fails

### ISSUE THREAD

**Issue by christophbossmann** [liquibase/liquibase-data#36]
When I try to run `liquibase data install` the below outlined error occures. However, the environment variable `TERM=xterm` has been set. Error:

```
C:\Program Files\liquibase>liquibase data install --log-level SEVERE
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starte Liquibase am 23:49:41 (Version 4.7.0 #1140, kompiliert am 2022-01-07 19:26+0000)
Liquibase Version: 4.7.0
Liquibase Community 4.7.0 by Liquibase
Initializing titan infrastructure ...
Checking docker installation   1% ←[33m??                                              ?←[0m   1/100 (0:00:00 / 0:00:09)
Checking docker installation   2% ←[33m??                                              ?←[0m   2/100 (0:00:00 / 0:00:14)Checking docker installation   3% ←[33m???                                             ?←[0m   3/100 (0:00:00 / 0:00:15)Checking docker installation   5% ←[33m????                                            ?←[0m   5/100 (0:00:00 / 0:00:16)Checking docker installation 100% ←[33m?????????????????????????????????????????????????←[0m 100/100 (0:00:01 / 0:00:00)[2022-05-13 23:49:44] SCHWERWIEGEND [liquibase.integration] java.lang.NumberFormatException: For input string: "5
latest
"
liquibase.exception.CommandExecutionException: java.lang.NumberFormatException: For input string: "5
latest
"
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: java.lang.NumberFormatException: For input string: "5
latest
"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.titandata.titan.Version$Companion.fromString(Version.kt:29)
        at io.titandata.titan.clients.Docker.titanLatestIsDownloaded(Docker.kt:54)
        at io.titandata.titan.providers.local.Install.install(Install.kt:26)
        at io.titandata.titan.providers.Local.install(Local.kt:159)
        at org.liquibase.ext.data.InstallCommandStep.run(InstallCommandStep.kt:18)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 14 more


Unexpected error running Liquibase: java.lang.NumberFormatException: For input string: "5
latest
"

liquibase.exception.CommandExecutionException: java.lang.NumberFormatException: For input string: "5
latest
"
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: java.lang.NumberFormatException: For input string: "5
latest
"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.titandata.titan.Version$Companion.fromString(Version.kt:29)
        at io.titandata.titan.clients.Docker.titanLatestIsDownloaded(Docker.kt:54)
        at io.titandata.titan.providers.local.Install.install(Install.kt:26)
        at io.titandata.titan.providers.Local.install(Local.kt:159)
        at org.liquibase.ext.data.InstallCommandStep.run(InstallCommandStep.kt:18)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 14 more
```

I'm running liquibase on version 4.7.0 and liquibase-data on version 0.0.7. To me it seemed that the error has to be something to with the titan version. However, by running the command `titan --version`, the resulting version is `titan version 0.5.4`. The docker version running is `Docker version 20.10.14, build a224086`

**Comment by mcred** [comment]
Thanks for including the docker version. What's the version of docker desktop? This looks like the command prompt. Which version of windows are you using? What is the output from `docker images` (feel free to remove not titan or liquibase releated)?

**Comment by christophbossmann** [comment]
Thanks for your quick response! I'm using Windows 10 Education, Version 20H2. The Docker Desktop Version I'm using is 4.8.0 (78933). The output of `docker images` is: 

```
C:\WINDOWS\system32>docker images
REPOSITORY                            TAG        IMAGE ID       CREATED         SIZE
zfs-builder-linuxkit                  0SlyBIBf   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  1xVUibIH   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  3FCd1l0g   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  4xIddO9l   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  5FPly2sX   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  6DbDpM7y   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  7Qq4ZcNN   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  8KjVCyTI   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  A3Yn1h2b   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  Axj9P8q8   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  CT31wPNd   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  CyBuXjqU   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  Fj3WoQs3   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  GYeAZwHU   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  Iydv1AkJ   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  K4YcvRSg   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  KPvuldYb   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  NLgxS2FC   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  NuwyEkOs   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  OeFJ15ZM   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  SGdNAmc4   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  U6oT7GU2   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  UoeN9Ptn   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  V6CQWW5h   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  WY5OPmdR   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  Z2031K40   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  bl1J1mXW   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  cFbyso0k   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  ccvjnSUc   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  chs9k921   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  cmRmUdX0   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  cwBJfSCF   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  cxUthUhz   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  fluzNJLX   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  gIEcfj8D   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  kiKe5P2D   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  lMtu6o18   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  lkLZpoGS   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  mz41W1v6   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  obbtz2Rh   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  p96azDup   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  q0q2G4iq   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  r5poMv8t   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  rcPzd4iC   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  sJAxZMKU   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  uLQQysE6   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  vduy8Iue   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  x1FFz6mD   279c34278fae   7 days ago      1.12GB
zfs-builder-linuxkit                  xLmzLrNx   279c34278fae   7 days ago      1.12GB
titandata/docker-desktop-zfs-kernel   5.10.104   743f1858e786   3 weeks ago     61.9MB
postgres                              latest     74b0c105737a   3 weeks ago     376MB
titan                                 0.8.5      fe0732b216e4   7 months ago    1.86GB
titan                                 latest     fe0732b216e4   7 months ago    1.86GB
titandata/titan                       0.8.5      fe0732b216e4   7 months ago    1.86GB
titandata/zfs-builder                 latest     6736d0dde6de   20 months ago   850MB
```

**Comment by mcred** [comment]
@christophbossmann Thanks for this info! We're currently in the middle of debugging some issues with Docker Desktop 4.8.0+. Feel free to stop any running titan containers and remove all the `zfs-builder-linuxkit` containers. I expect to have this issue resolved in the next day or two. I will let you know ASAP when you can re-run the install steps.

**Comment by mcred** [comment]
@christophbossmann I just confirmed installation for Docker Desktop 4.8.2 on both AMD and ARM architecture. Run `liquibase data uninstall` (just to be safe) and then `liquibase data install`. This should fix the issue you ran into. Let me know how it goes!

**Comment by christophbossmann** [comment]
@mcred  Thanks for the hint to update the docker desktop version to 4.8.2 and to remove the docker container and images. After running `liquibase data uninstall`, removing all docker containers and images and running `liquibase data install` again, it worked! The issue can be closed!

**Comment by mcred** [comment]
Glad to hear it!
